# Generated by Django 5.2.3 on 2025-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
