# Generated by Django 5.2.3 on 2025-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_snippet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('', '--- Выберите язык ---'), ('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javaScript', 'JavaScript'), ('html', 'HTML')], max_length=10),
        ),
    ]
