# Generated by Django 5.2.3 on 2025-07-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_comment_snippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('name',)},
        ),
    ]
