# Generated by Django 5.2.3 on 2025-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_alter_comment_id_alter_snippet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
