# Generated by Django 5.2.3 on 2025-08-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MainApp.snippet'),
        ),
    ]
