# Generated by Django 5.2.3 on 2025-09-03 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['public'], name='MainApp_sni_public_f4f309_idx'),
        ),
    ]
