# Generated by Django 5.2.3 on 2025-09-03 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_alter_snippet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['public', 'user'], name='MainApp_sni_public_58ca88_idx'),
        ),
    ]
