# Generated by Django 5.2.3 on 2025-09-03 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_snippet_mainapp_sni_public_58ca88_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['id', 'user', 'public'], name='MainApp_sni_id_2a460c_idx'),
        ),
    ]
