# Generated by Django 5.2.3 on 2025-09-03 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_snippet_mainapp_sni_id_2a460c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['name', 'lang']},
        ),
        migrations.RemoveIndex(
            model_name='snippet',
            name='MainApp_sni_public_f4f309_idx',
        ),
        migrations.RemoveIndex(
            model_name='snippet',
            name='MainApp_sni_id_2a460c_idx',
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['name', 'lang'], name='MainApp_sni_name_48c470_idx'),
        ),
    ]
