# Generated by Django 5.2.3 on 2025-09-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_snippet_mainapp_sni_user_id_2c247a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='snippet',
            name='MainApp_sni_public_58ca88_idx',
        ),
    ]
