# Generated by Django 5.2.3 on 2025-09-03 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_remove_snippet_mainapp_sni_public_58ca88_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='MainApp_not_is_read_d3adfe_idx'),
        ),
    ]
