# Generated by Django 5.2.3 on 2025-09-03 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_remove_notification_mainapp_not_is_read_d3adfe_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='MainApp_not_created_ae96a6_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='MainApp_not_is_read_c34038_idx'),
        ),
    ]
