# Generated by Django 5.2.3 on 2025-09-03 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_remove_notification_mainapp_not_created_ae96a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at', 'is_read'], name='MainApp_not_created_f6372f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='MainApp_not_created_ae96a6_idx'),
        ),
    ]
