# Generated by Django 5.2.3 on 2025-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Новый комментарий'), ('like', 'Новый лайк'), ('follow', 'Новый подписчик'), ('snippet_update', 'Обновление сниппета')], max_length=20),
        ),
    ]
